### PR TITLE
fix exit codes of binaries

### LINKED ISSUE #169: Failed to render Liquid template on CRUD controller
```
>cargo generate crud-controller tasks
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running `target\debug\generate.exe crud-controller tasks`
ℹ️  Generating CRUD controller…
✅ Generated CRUD controller ./web/src/controllers/tasks.rs.
ℹ️  Do not forget to route the controller's actions in ./web/src/routes.rs!
ℹ️  Generating test for CRUD controller…
❌ Could not generate test for CRUD controller!
Failed to render Liquid template

Caused by:
    liquid: Unknown variable
      with:
        requested variable=crate_name
```

# Version this is generated by
`gerust 0.0.3` (via `cargo install gerust`)

### PR DESCRIPTION
**Pull request by marcoow**
This fixes the exit codes of the project binaries that currently swallow any errors (they log the errors but always return a successful exit code. That's not critical when working with the binaries in development but leads to bugs like #169 going unnoticed in CI…

The code is quite repetitive now and could use some cleanup eventually.

This also fixes 2 actual errors in the generators which fix CI (which now correctly fails because of these errors).

closes #169

### CODE REVIEW

**Comment by datenzauberer** [comment]
Executing `cargo generate crud-controller tasks` does not generate the test for the CRUD controller (`./web/tests/api/tasks_test.rs` is missing).
However, using the fix from [PR #172](https://github.com/mainmatter/gerust/pull/172) resolves this issue and works as expected.

Is there anything blocking the merge of this PR? I’d be happy to support if needed. Please let me know how I can assist.

File: blueprint/cli/src/bin/db.rs [hunk 1]
```diff
@@ -65,105 +67,131 @@ async fn cli() {
...
+                            ui.outdent();
+                            ui.success(&format!("Reset database {} successfully.", db_name));
+                            Ok(())
+                        }
+                        Err(e) => {
+                            ui.outdent();
+                            ui.error("Could not reset database!", &e);
+                            Err(e)
+                        }
+                    }
```
Comment (LukeMathWalker) [inline blueprint/cli/src/bin/db.rs:141]: I'm not super fond of the pattern here, where we log the error manually in every single place.
I think it'd be more robust to do this logging in the `main` function above, before exiting with a non-zero code.

I imagine this was originally done to control the message shown to the user. We can achieve the same goal with the following structure:

```suggestion
                    let outcome = reset(&mut ui, &config.database).await.context("Could not reset the database!");
                    ui.outdent();
                    let db_name = outcome?; 
                    ui.success(&format!("Reset database {} successfully.", db_name));
                    Ok(())
```

and in `main`:

```rust
 match cli().await {
        Ok(_) => ExitCode::SUCCESS,
        Err(e) => {
            ui.error(e.to_string(), &e);
            ExitCode::FAILURE,
        }
    }
```

Comment (LukeMathWalker) [reply blueprint/cli/src/bin/db.rs:141]: Ideally `ui.error` would just take the error, relying on its `Display` implementation, rather than forcing the caller to invoke `e.to_string()`, but that can be fixed later.

Comment (marcoow) [reply blueprint/cli/src/bin/db.rs]: fixed

File: blueprint/cli/src/bin/db.rs [hunk 2]
```diff
@@ -56,114 +67,98 @@ enum Commands {
...
-                        ui.outdent();
-                        ui.success(&format!("{} migrations applied.", migrations));
-                    }
-                    Err(e) => {
-                        ui.outdent();
-                        ui.error("Could not migrate database!", e);
-                    }
+                Commands::Migrate => {
+                    ui.info(&format!("Migrating {} database…", &cli.env));
+                    ui.indent();
```
Comment (LukeMathWalker) [inline blueprint/cli/src/bin/db.rs:93]: This needs to be outdented before raising the error with `?`.

File: src/main.rs [hunk 3]
```diff
@@ -110,7 +110,7 @@ async fn main() {
         }
         Err(e) => {
             ui.outdent();
-            ui.error("Could not generate project!", e);
+            ui.error("Could not generate project!", &e);
```
Comment (LukeMathWalker) [inline src/main.rs:113]: We need to exit with an error code here too.

File: blueprint/cli/src/bin/db.rs [hunk 4]
```diff
@@ -56,114 +67,97 @@ enum Commands {
...
+                    let migrations = migrate(&mut ui, &config.database)
+                        .await
+                        .context("Could not migrate database!")?;
+                    ui.outdent();
```
Comment (LukeMathWalker) [inline blueprint/cli/src/bin/db.rs:97]:
```suggestion
                    let migrations = migrate(&mut ui, &config.database)
                        .await
                        .context("Could not migrate database!");
                    ui.outdent();
                    let migrations = migrations?;
```

Comment (LukeMathWalker) [reply blueprint/cli/src/bin/db.rs:97]: Otherwise you only outdent on the happy path.

File: blueprint/cli/src/bin/db.rs [hunk 5]
```diff
@@ -56,114 +67,97 @@ enum Commands {
...
+                        let mut cmd = tokio::process::Command::new(&cargo);
+                
+                        cmd.args(["sqlx", "prepare", "--", "--all-targets", "--all-features"]);
+                
+                        let cmd_cwd = match db_package_root() {
+                            Ok(cwd) => cwd,
+                            Err(e) => {
+                                return Err(e.context("Error finding the root of the db package!"));
+                            }
+                        };
```
Comment (LukeMathWalker) [inline blueprint/cli/src/bin/db.rs:137]:
```suggestion
                        let cmd_cwd = db_package_root().context("Error finding the root of the db package!")?;
```
